name: Update Readme
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/6 * * *'
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.1.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
  recent-activity:
    name: Update Readme with Recent Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: BrandgrandRealMe/github-activity-readme@v0.3.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update Recent Activity'
  waka-metrics:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: True
          SHOW_LINES_OF_CODE: True
          
