name: Update Readme
on:
  schedule:
    # runs at 12 am every day
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  recent-activity:
    name: Update Readme with Recent Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update Recent Activity'
  waka-metrics:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: True
          SHOW_LINES_OF_CODE: True
          
