name: Update Readme
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      PIN_OPS: show_owner=true&theme=radical&hide_border=true&username=Davenchy&description_lines_count=3
    steps:
      - uses: actions/checkout@v6
      
      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: theme=radical&hide_border=true&include_all_commits=true&count_private=false&show_icons=true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: theme=radical&hide_border=true&include_all_commits=true&count_private=true&layout=compact&langs_count=10
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate wakatime card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: wakatime
          options: theme=radical&hide_border=true&show_icons=true&layout=compact&langs_count=10
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate streak stats card
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=radical&disable_animations=true&hide_border=true&mode=weekly
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate trophy card
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: username=${{ github.repository_owner }}&theme=radical&column=4&margin-w=15&margin-h=15&no-frame=true
          path: profile/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for live-torrent-backend repo
        uses: stats-organization/github-readme-stats-action@v2
        env:
          REPO: live-torrent-backend
        with:
          card: pin
          options: ${{ env.PIN_OPS }}&repo=${{ env.REPO }}
          path: profile/repos/${{ env.REPO }}-pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for media-share repo
        uses: stats-organization/github-readme-stats-action@v2
        env:
          REPO: media-share
        with:
          card: pin
          options: ${{ env.PIN_OPS }}&repo=${{ env.REPO }}
          path: profile/repos/${{ env.REPO }}-pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for clayout repo
        uses: stats-organization/github-readme-stats-action@v2
        env:
          REPO: clayout
        with:
          card: pin
          options: ${{ env.PIN_OPS }}&repo=${{ env.REPO }}
          path: profile/repos/${{ env.REPO }}-pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for brainfuck_compiler.rs repo
        uses: stats-organization/github-readme-stats-action@v2
        env:
          REPO: brainfuck_compiler.rs
        with:
          card: pin
          options: ${{ env.PIN_OPS }}&repo=${{ env.REPO }}
          path: profile/repos/${{ env.REPO }}-pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for qemu-arm-machine repo
        uses: stats-organization/github-readme-stats-action@v2
        env:
          REPO: qemu-arm-machine
        with:
          card: pin
          options: ${{ env.PIN_OPS }}&repo=${{ env.REPO }}
          path: profile/repos/${{ env.REPO }}-pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for rusty_battleship repo
        uses: stats-organization/github-readme-stats-action@v2
        env:
          REPO: rusty_battleship
        with:
          card: pin
          options: ${{ env.PIN_OPS }}&repo=${{ env.REPO }}
          path: profile/repos/${{ env.REPO }}-pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for service_generator repo
        uses: stats-organization/github-readme-stats-action@v2
        env:
          REPO: service_generator
        with:
          card: pin
          options: ${{ env.PIN_OPS }}&repo=${{ env.REPO }}
          path: profile/repos/${{ env.REPO }}-pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for pc-remote repo
        uses: stats-organization/github-readme-stats-action@v2
        env:
          REPO: pc-remote
        with:
          card: pin
          options: ${{ env.PIN_OPS }}&repo=${{ env.REPO }}
          path: profile/repos/${{ env.REPO }}-pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for hotclip repo
        uses: stats-organization/github-readme-stats-action@v2
        env:
          REPO: hotclip
        with:
          card: pin
          options: ${{ env.PIN_OPS }}&repo=${{ env.REPO }}
          path: profile/repos/${{ env.REPO }}-pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for timer_sh repo
        uses: stats-organization/github-readme-stats-action@v2
        env:
          REPO: timer_sh
        with:
          card: pin
          options: ${{ env.PIN_OPS }}&repo=${{ env.REPO }}
          path: profile/repos/${{ env.REPO }}-pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for lox-ts repo
        uses: stats-organization/github-readme-stats-action@v2
        env:
          REPO: lox-ts
        with:
          card: pin
          options: ${{ env.PIN_OPS }}&repo=${{ env.REPO }}
          path: profile/repos/${{ env.REPO }}-pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "davenchy-bot@users.noreply.github.com"
          git add profile/*.svg
          git add profile/repos/*.svg
          git commit -m "Update README cards [WORKFLOW_ACTION]" || exit 0
          git push
  # devcard:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: devcard
  #       uses: dailydotdev/action-devcard@2.1.0
  #       with:
  #         devcard_id: ${{ secrets.DEVCARD_ID }}
  # recent-activity:
  #   name: Update Readme with Recent Activity
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: BrandgrandRealMe/github-activity-readme@v0.3.8
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         COMMIT_MSG: 'Update Recent Activity'
  # waka-metrics:
  #   name: Update Readme with Metrics
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: anmol098/waka-readme-stats@master
  #       with:
  #         WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #         SHOW_UPDATED_DATE: True
  #         SHOW_LINES_OF_CODE: True
  
